package com.stalm12.webshelf.security;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Service for encrypting and decrypting sensitive data using AES-256-GCM.
 * 
 * This service provides authenticated encryption with associated data (AEAD) using
 * AES in GCM (Galois/Counter Mode), which provides both confidentiality and authenticity.
 * Each encryption operation generates a unique 96-bit nonce to ensure that identical
 * plaintexts produce different ciphertexts.
 * 
 * <p>The master encryption key can be configured via the {@code app.encryption-key}
 * property (Base64-encoded 256-bit key). If not configured, a random key is generated
 * for the application lifetime (not persistent across restarts).</p>
 * 
 * <p><strong>Security Properties:</strong></p>
 * <ul>
 *   <li>Algorithm: AES-256-GCM (NIST-approved AEAD cipher)</li>
 *   <li>Key size: 256 bits</li>
 *   <li>Nonce size: 96 bits (randomly generated per encryption)</li>
 *   <li>Authentication tag: 128 bits</li>
 *   <li>Integrity verification: Automatic via GCM authentication tag</li>
 *   <li>Tamper detection: Exception raised on decryption failure</li>
 * </ul>
 */
@Service
public class EncryptionService {

    private static final String ALGORITHM = "AES/GCM/NoPadding";
    private static final String KEY_ALGORITHM = "AES";
    private static final int KEY_SIZE = 256;
    private static final int GCM_NONCE_LENGTH = 12; // 96 bits for GCM
    private static final int GCM_TAG_LENGTH = 128; // 128 bits (16 bytes)
    private final SecretKey masterKey;
    private final SecureRandom random = new SecureRandom();

    /**
     * Initializes the EncryptionService with a master encryption key.
     * 
     * @param encryptionKeyBase64 Base64-encoded 256-bit AES key. If null or empty,
     *                            a random key is generated for the application lifetime.
     *                            To generate a persistent key, use:
     *                            {@code openssl rand -base64 32}
     */
    public EncryptionService(@Value("${app.encryption-key:}") String encryptionKeyBase64) {
        if (encryptionKeyBase64 == null || encryptionKeyBase64.isBlank()) {
            this.masterKey = generateRandomKey();
        } else {
            this.masterKey = decodeKeyFromBase64(encryptionKeyBase64);
        }
    }

    /**
     * Encrypts a plaintext string using AES-256-GCM with a unique random nonce.
     * 
     * <p>The encrypted output includes the nonce, ciphertext, and authentication tag,
     * all encoded in Base64 for storage in the database. The nonce ensures that encrypting
     * the same plaintext multiple times produces different ciphertexts.</p>
     * 
     * <p>Format of returned string: {@code Base64(nonce || ciphertext || auth_tag)}</p>
     * 
     * @param plaintext the text to encrypt (null returns null)
     * @return Base64-encoded encrypted data containing nonce, ciphertext, and authentication tag
     * @throws Exception if encryption fails (e.g., invalid plaintext encoding)
     */
    public String encrypt(String plaintext) throws Exception {
        if (plaintext == null) {
            return null;
        }

        byte[] nonce = new byte[GCM_NONCE_LENGTH];
        random.nextBytes(nonce);

        Cipher cipher = Cipher.getInstance(ALGORITHM);
        GCMParameterSpec gcmSpec = new GCMParameterSpec(GCM_TAG_LENGTH, nonce);
        cipher.init(Cipher.ENCRYPT_MODE, masterKey, gcmSpec);

        byte[] plaintextBytes = plaintext.getBytes(StandardCharsets.UTF_8);
        byte[] encryptedBytes = cipher.doFinal(plaintextBytes);

        byte[] nonceAndCiphertext = new byte[GCM_NONCE_LENGTH + encryptedBytes.length];
        System.arraycopy(nonce, 0, nonceAndCiphertext, 0, GCM_NONCE_LENGTH);
        System.arraycopy(encryptedBytes, 0, nonceAndCiphertext, GCM_NONCE_LENGTH, encryptedBytes.length);

        return Base64.getEncoder().encodeToString(nonceAndCiphertext);
    }

    /**
     * Decrypts a Base64-encoded ciphertext string using AES-256-GCM.
     * 
     * <p>This method automatically extracts the nonce from the encrypted data and verifies
     * the GCM authentication tag. If the tag verification fails (indicating tampering or
     * corrupted data), a {@link javax.crypto.AEADBadTagException} is raised.</p>
     * 
     * <p>Expected input format: {@code Base64(nonce || ciphertext || auth_tag)}</p>
     * 
     * @param encryptedText Base64-encoded encrypted data (must be generated by {@link #encrypt(String)})
     * @return the decrypted plaintext (null if encryptedText is null)
     * @throws IllegalArgumentException if the encrypted data is malformed or too short
     * @throws javax.crypto.AEADBadTagException if authentication tag verification fails
     *         (indicates tampering or data corruption)
     * @throws Exception for other decryption errors
     */
    public String decrypt(String encryptedText) throws Exception {
        if (encryptedText == null) {
            return null;
        }

        byte[] nonceAndCiphertext = Base64.getDecoder().decode(encryptedText);

        if (nonceAndCiphertext.length < GCM_NONCE_LENGTH) {
            throw new IllegalArgumentException("Invalid encrypted data: too short");
        }

        byte[] nonce = new byte[GCM_NONCE_LENGTH];
        System.arraycopy(nonceAndCiphertext, 0, nonce, 0, GCM_NONCE_LENGTH);

        byte[] ciphertextBytes = new byte[nonceAndCiphertext.length - GCM_NONCE_LENGTH];
        System.arraycopy(nonceAndCiphertext, GCM_NONCE_LENGTH, ciphertextBytes, 0, ciphertextBytes.length);

        Cipher cipher = Cipher.getInstance(ALGORITHM);
        GCMParameterSpec gcmSpec = new GCMParameterSpec(GCM_TAG_LENGTH, nonce);
        cipher.init(Cipher.DECRYPT_MODE, masterKey, gcmSpec);

        byte[] decryptedBytes = cipher.doFinal(ciphertextBytes);
        return new String(decryptedBytes, StandardCharsets.UTF_8);
    }

    /**
     * Generates a random 256-bit AES master key.
     * 
     * <p>This method is used when no encryption key is provided via configuration.
     * The generated key is not persistent and will be regenerated on application restart,
     * making any previously encrypted data unrecoverable.</p>
     * 
     * @return a randomly generated 256-bit AES key
     * @throws RuntimeException if key generation fails
     */
    private SecretKey generateRandomKey() {
        try {
            KeyGenerator keyGenerator = KeyGenerator.getInstance(KEY_ALGORITHM);
            keyGenerator.init(KEY_SIZE);
            return keyGenerator.generateKey();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate encryption key", e);
        }
    }

    /**
     * Decodes a Base64-encoded AES master key.
     * 
     * <p>This method is used to restore a persistent encryption key from configuration
     * (e.g., from an environment variable). The decoded key must be exactly 256 bits (32 bytes).</p>
     * 
     * <p>To generate a Base64-encoded key:
     * {@code openssl rand -base64 32}</p>
     * 
     * @param encodedKey Base64-encoded 256-bit AES key
     * @return the decoded AES SecretKey
     * @throws RuntimeException if the key cannot be decoded or is invalid
     */
    private SecretKey decodeKeyFromBase64(String encodedKey) {
        try {
            byte[] decodedKey = Base64.getDecoder().decode(encodedKey);
            return new SecretKeySpec(decodedKey, 0, decodedKey.length, KEY_ALGORITHM);
        } catch (Exception e) {
            throw new RuntimeException("Failed to decode encryption key from Base64", e);
        }
    }
}

